---
title: "feather:在R与python之间共享数据存储格式"
author: William
date: 2020-04-15
lastmod: 2020-04-15
categories: [Programming]
tags: [feather,R,python,数据存储]
description: feather 提供了快速序列化数据的文件存储格式，能够实现在　Ｒ 与　Python 之间共享数据存储对象。 
draft: false
ToC: true
---





# 使用 R 与 Python 共同的数据存储文件格式：feather

项目的详细介绍在github: https://github.com/wesm/feather

## python

```bash
pip install feather-format
```

## R

```r
install.packages("feather")
```


```bash
%%bash
ls -alh /home/william/20200414
```

    total 2.4G
    drwx------   2 william william 4.0K Apr 15 17:57 .
    drwxr-xr-x 107 william william  12K Apr 15 17:57 ..
    -rw-r--r--   1 william william 6.4K Apr 14 08:37 commission.csv
    -rw-r--r--   1 william william 1.6M Apr 14 08:37 instrument.csv
    -rw-r--r--   1 william william 2.4G Apr 14 15:32 tick.csv


## 性能测试: python


```python
import pandas as pd
import numpy as np
import feather
```


```python
%time tick_csv = pd.read_csv("/home/william/20200414/tick.csv")
for col in tick_csv.columns[6:]:
    tick_csv[col] = tick_csv[col].astype(float)
```

    <string>:2: DtypeWarning: Columns (6,7,13,14,15,16,17,19) have mixed types.Specify dtype option on import or set low_memory=False.


    CPU times: user 37.1 s, sys: 3.31 s, total: 40.4 s
    Wall time: 41.1 s



```python
tick_csv.head(10)
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }


    .dataframe tbody tr th {
        vertical-align: top;
    }
    
    .dataframe thead th {
        text-align: right;
    }

</style>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Timestamp</th>
      <th>TradingDay</th>
      <th>UpdateTime</th>
      <th>UpdateMillisec</th>
      <th>ExchangeID</th>
      <th>InstrumentID</th>
      <th>LastPrice</th>
      <th>PreClosePrice</th>
      <th>OpenPrice</th>
      <th>HighestPrice</th>
      <th>...</th>
      <th>Volume</th>
      <th>Turnover</th>
      <th>OpenInterest</th>
      <th>UpperLimitPrice</th>
      <th>LowerLimitPrice</th>
      <th>BidPrice1</th>
      <th>BidVolume1</th>
      <th>AskPrice1</th>
      <th>AskVolume1</th>
      <th>AveragePrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2020-04-14 08:35:18.630311674</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>hc2011</td>
      <td>3225.0</td>
      <td>3225.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>28.0</td>
      <td>3429.00</td>
      <td>2980.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2020-04-14 08:35:18.630385219</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>wr2011</td>
      <td>3745.0</td>
      <td>3745.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>4007.00</td>
      <td>3482.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2020-04-14 08:35:18.630399462</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>au2012</td>
      <td>375.9</td>
      <td>375.9</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>39922.0</td>
      <td>398.04</td>
      <td>352.98</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2020-04-14 08:35:18.630411353</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>rb2011</td>
      <td>3345.0</td>
      <td>3345.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1086.0</td>
      <td>3581.00</td>
      <td>3112.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2020-04-14 08:35:18.630423833</td>
      <td>20200414</td>
      <td>07:25:23</td>
      <td>0</td>
      <td>NaN</td>
      <td>CF009C14800</td>
      <td>115.0</td>
      <td>115.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1163.0</td>
      <td>808.00</td>
      <td>1.00</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2020-04-14 08:35:18.630444816</td>
      <td>20200414</td>
      <td>07:25:23</td>
      <td>0</td>
      <td>NaN</td>
      <td>CF009C14600</td>
      <td>114.0</td>
      <td>114.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1427.0</td>
      <td>819.00</td>
      <td>1.00</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2020-04-14 08:35:18.630454968</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>fu2008</td>
      <td>1679.0</td>
      <td>1679.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>91250.0</td>
      <td>1893.00</td>
      <td>1548.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2020-04-14 08:35:18.630483849</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>sc2008</td>
      <td>300.2</td>
      <td>300.2</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>10966.0</td>
      <td>340.20</td>
      <td>278.30</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2020-04-14 08:35:18.630496127</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>bu2006</td>
      <td>2156.0</td>
      <td>2156.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>468416.0</td>
      <td>2422.00</td>
      <td>1980.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2020-04-14 08:35:18.630507034</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>sc2109</td>
      <td>371.0</td>
      <td>371.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>42.0</td>
      <td>408.10</td>
      <td>333.90</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>10 rows × 22 columns</p>

</div>




```python
len(tick_csv)
```




    13373363




```python
## 写文件相对比较慢，因为要做序列化
%time tick_csv.to_feather("/home/william/20200414/tick.feather")
```

    CPU times: user 3.26 s, sys: 1.49 s, total: 4.75 s
    Wall time: 6.13 s



```python
## 读文件非常快
%time tick_feather = pd.read_feather("/home/william/20200414/tick.feather")
```

    CPU times: user 4.34 s, sys: 1.51 s, total: 5.85 s
    Wall time: 5.15 s



```python
tick_feather.head(10)
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }


    .dataframe tbody tr th {
        vertical-align: top;
    }
    
    .dataframe thead th {
        text-align: right;
    }

</style>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Timestamp</th>
      <th>TradingDay</th>
      <th>UpdateTime</th>
      <th>UpdateMillisec</th>
      <th>ExchangeID</th>
      <th>InstrumentID</th>
      <th>LastPrice</th>
      <th>PreClosePrice</th>
      <th>OpenPrice</th>
      <th>HighestPrice</th>
      <th>...</th>
      <th>Volume</th>
      <th>Turnover</th>
      <th>OpenInterest</th>
      <th>UpperLimitPrice</th>
      <th>LowerLimitPrice</th>
      <th>BidPrice1</th>
      <th>BidVolume1</th>
      <th>AskPrice1</th>
      <th>AskVolume1</th>
      <th>AveragePrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2020-04-14 08:35:18.630311674</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>hc2011</td>
      <td>3225.0</td>
      <td>3225.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>28.0</td>
      <td>3429.00</td>
      <td>2980.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2020-04-14 08:35:18.630385219</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>wr2011</td>
      <td>3745.0</td>
      <td>3745.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>4007.00</td>
      <td>3482.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2020-04-14 08:35:18.630399462</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>au2012</td>
      <td>375.9</td>
      <td>375.9</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>39922.0</td>
      <td>398.04</td>
      <td>352.98</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2020-04-14 08:35:18.630411353</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>rb2011</td>
      <td>3345.0</td>
      <td>3345.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1086.0</td>
      <td>3581.00</td>
      <td>3112.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2020-04-14 08:35:18.630423833</td>
      <td>20200414</td>
      <td>07:25:23</td>
      <td>0</td>
      <td>NaN</td>
      <td>CF009C14800</td>
      <td>115.0</td>
      <td>115.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1163.0</td>
      <td>808.00</td>
      <td>1.00</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2020-04-14 08:35:18.630444816</td>
      <td>20200414</td>
      <td>07:25:23</td>
      <td>0</td>
      <td>NaN</td>
      <td>CF009C14600</td>
      <td>114.0</td>
      <td>114.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1427.0</td>
      <td>819.00</td>
      <td>1.00</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2020-04-14 08:35:18.630454968</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>fu2008</td>
      <td>1679.0</td>
      <td>1679.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>91250.0</td>
      <td>1893.00</td>
      <td>1548.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2020-04-14 08:35:18.630483849</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>sc2008</td>
      <td>300.2</td>
      <td>300.2</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>10966.0</td>
      <td>340.20</td>
      <td>278.30</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2020-04-14 08:35:18.630496127</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>bu2006</td>
      <td>2156.0</td>
      <td>2156.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>468416.0</td>
      <td>2422.00</td>
      <td>1980.00</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2020-04-14 08:35:18.630507034</td>
      <td>20200414</td>
      <td>07:20:49</td>
      <td>500</td>
      <td>NaN</td>
      <td>sc2109</td>
      <td>371.0</td>
      <td>371.0</td>
      <td>1.797693e+308</td>
      <td>1.797693e+308</td>
      <td>...</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>42.0</td>
      <td>408.10</td>
      <td>333.90</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>1.797693e+308</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>10 rows × 22 columns</p>

</div>




```python
len(tick_feather)
```




    13373363



## 性能测试: R


```python
%load_ext rpy2.ipython
```


```r
%%R
library(data.table)
```


```r
%%R
system.time({dt <- fread('/home/william/20200414/tick.csv', verbose = FALSE, showProgress = FALSE)})
```

       user  system elapsed 
     63.591   1.474  18.146 



```r
%%R
head(dt)
```

                           Timestamp TradingDay UpdateTime UpdateMillisec ExchangeID InstrumentID LastPrice PreClosePrice
    1: 2020-04-14 08:35:18.630311674   20200414   07:20:49            500         NA       hc2011    3225.0        3225.0
    2: 2020-04-14 08:35:18.630385219   20200414   07:20:49            500         NA       wr2011    3745.0        3745.0
    3: 2020-04-14 08:35:18.630399462   20200414   07:20:49            500         NA       au2012     375.9         375.9
    4: 2020-04-14 08:35:18.630411353   20200414   07:20:49            500         NA       rb2011    3345.0        3345.0
    5: 2020-04-14 08:35:18.630423833   20200414   07:25:23              0         NA  CF009C14800     115.0         115.0
    6: 2020-04-14 08:35:18.630444816   20200414   07:25:23              0         NA  CF009C14600     114.0         114.0
                                                                                                                                                                                                                                                                                                                   OpenPrice
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
                                                                                                                                                                                                                                                                                                                HighestPrice
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
                                                                                                                                                                                                                                                                                                                 LowestPrice
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
                                                                                                                                                                                                                                                                                                                  ClosePrice
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
       Volume Turnover OpenInterest UpperLimitPrice LowerLimitPrice
    1:      0        0           28            3429            2980
    2:      0        0            0            4007            3482
    3:      0        0        39922             398             353
    4:      0        0         1086            3581            3112
    5:      0        0         1163             808               1
    6:      0        0         1427             819               1
                                                                                                                                                                                                                                                                                                                   BidPrice1
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
       BidVolume1
    1:          0
    2:          0
    3:          0
    4:          0
    5:          0
    6:          0
                                                                                                                                                                                                                                                                                                                   AskPrice1
    1: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    2: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    3: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    4: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368
    5:                                                                                                                                                                                                                                                                                                                     0
    6:                                                                                                                                                                                                                                                                                                                     0
       AskVolume1 AveragePrice
    1:          0            0
    2:          0            0
    3:          0            0
    4:          0            0
    5:          0            0
    6:          0            0



```r
%%R
system.time({dt_feather <- feather::read_feather('/home/william/20200414/tick.feather')})
```

       user  system elapsed 
      8.342   0.761   9.112 



```r
%%R
head(dt_feather)
```

    [90m# A tibble: 6 x 22[39m
      Timestamp TradingDay UpdateTime UpdateMillisec ExchangeID InstrumentID LastPrice PreClosePrice OpenPrice HighestPrice
      [3m[90m<chr>[39m[23m          [3m[90m<dbl>[39m[23m [3m[90m<chr>[39m[23m               [3m[90m<dbl>[39m[23m      [3m[90m<dbl>[39m[23m [3m[90m<chr>[39m[23m            [3m[90m<dbl>[39m[23m         [3m[90m<dbl>[39m[23m     [3m[90m<dbl>[39m[23m        [3m[90m<dbl>[39m[23m
    [90m1[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:20:49              500         [31mNA[39m hc2011           [4m3[24m225          [4m3[24m225   1.80[90me[39m308     1.80[90me[39m308
    [90m2[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:20:49              500         [31mNA[39m wr2011           [4m3[24m745          [4m3[24m745   1.80[90me[39m308     1.80[90me[39m308
    [90m3[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:20:49              500         [31mNA[39m au2012            376.          376.  1.80[90me[39m308     1.80[90me[39m308
    [90m4[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:20:49              500         [31mNA[39m rb2011           [4m3[24m345          [4m3[24m345   1.80[90me[39m308     1.80[90me[39m308
    [90m5[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:25:23                0         [31mNA[39m CF009C14800       115           115   0.  [90m [39m        0.  [90m [39m   
    [90m6[39m 2020-04-…   20[4m2[24m[4m0[24m[4m0[24m414 07:25:23                0         [31mNA[39m CF009C14600       114           114   0.  [90m [39m        0.  [90m [39m   
    [90m# … with 12 more variables: LowestPrice [3m[90m<dbl>[90m[23m, ClosePrice [3m[90m<dbl>[90m[23m, Volume [3m[90m<dbl>[90m[23m, Turnover [3m[90m<dbl>[90m[23m, OpenInterest [3m[90m<dbl>[90m[23m,
    #   UpperLimitPrice [3m[90m<dbl>[90m[23m, LowerLimitPrice [3m[90m<dbl>[90m[23m, BidPrice1 [3m[90m<dbl>[90m[23m, BidVolume1 [3m[90m<dbl>[90m[23m, AskPrice1 [3m[90m<dbl>[90m[23m, AskVolume1 [3m[90m<dbl>[90m[23m,
    #   AveragePrice [3m[90m<dbl>[90m[23m[39m



```r
%%R
system.time({
    fst::write_fst(dt, "/home/william/20200414/tick.fst")
})
```

       user  system elapsed 
     10.718   1.065   4.356 



```r
%%R
system.time({
    dt_fst <- fst::read_fst("/home/william/20200414/tick.fst", as.data.table = TRUE)
})
```

       user  system elapsed 
      6.918   0.751   5.671 


# R -> Python


```python
from rpy2.robjects import r, pandas2ri
pandas2ri.activate()
```


```r
%%R
r_data = data.table(x = 1, y = 2)
```


```python
r.r_data
```




<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }


    .dataframe tbody tr th {
        vertical-align: top;
    }
    
    .dataframe thead th {
        text-align: right;
    }

</style>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>x</th>
      <th>y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1.0</td>
      <td>2.0</td>
    </tr>
  </tbody>
</table>

</div>




```python
py_data = r.r_data
```


```python
print(py_data)
```

         x    y
    1  1.0  2.0

